import 'reflect-metadata';
import { DependencyContainer } from 'tsyringe';
import { DatabaseConnector_Sequelize } from './database.connector.sequelize';
import { AddressRepo } from './repositories/general/address.repo';
import { CustomerRepo } from './repositories/customer/customer.repo';
import { DoctorRepo } from './repositories/users/doctor.repo';
import { KnowledgeNuggetRepo } from './repositories/educational/knowledge.nugget.repo';
import { FileResourceRepo } from './repositories/general/file.resource.repo';
import { InternalTestUserRepo } from './repositories/users/user/internal.test.user.repo';
import { OrganizationRepo } from './repositories/general/organization.repo';
import { OtpRepo } from './repositories/users/user/otp.repo';
import { EmergencyContactRepo } from './repositories/users/patient/emergency.contact.repo';
import { GoalRepo } from './repositories/users/patient/goal.repo';
import { HealthProfileRepo } from './repositories/users/patient/health.profile.repo';
import { PatientRepo } from './repositories/users/patient/patient.repo';
import { PersonRepo } from './repositories/person/person.repo';
import { PersonRoleRepo } from './repositories/person/person.role.repo';
import { RolePrivilegeRepo } from './repositories/role/role.privilege.repo';
import { RoleRepo } from './repositories/role/role.repo';
import { UserDeviceDetailsRepo } from './repositories/users/user/user.device.details.repo';
import { UserRepo } from './repositories/users/user/user.repo';
import { UserTaskRepo } from './repositories/users/user/user.task.repo';
import { CalorieBalanceRepo } from './repositories/wellness/daily.records/calorie.balance.repo';
import { HeartPointsRepo } from './repositories/wellness/daily.records/heart.points.repo';
import { MoveMinutesRepo } from './repositories/wellness/daily.records/move.minutes.repo';
import { SleepRepo } from './repositories/wellness/daily.records/sleep.repo';
import { StepCountRepo } from './repositories/wellness/daily.records/step.count.repo';
import { MeditationRepo } from './repositories/wellness/exercise/meditation.repo';
import { PhysicalActivityRepo } from './repositories/wellness/exercise/physical.activity.repo';
import { FoodConsumptionRepo } from './repositories/wellness/nutrition/food.consumption.repo';
import { WaterConsumptionRepo } from './repositories/wellness/nutrition/water.consumption.repo';
import { HealthPriorityRepo } from './repositories/users/patient/health.priority.repo';
import { ActionPlanRepo } from './repositories/users/patient/action.plan.repo';
import { ThirdpartyApiRepo } from './repositories/general/thirdparty.api.repo';
import { CustomTaskRepo } from './repositories/users/user/custom.task.repo';
import { FoodComponentMonitoringRepo } from './repositories/wellness/food.component.monitoring/food.component.monitoring.repo';
import { UserLoginSessionRepo } from './repositories/users/user/user.login.session.repo';
import { StandRepo } from './repositories/wellness/daily.records/stand.repo';
import { NoticeRepo } from './repositories/general/notice.repo';
import { LearningPathRepo } from './repositories/educational/learning/learning.path.repo';
import { CourseRepo } from './repositories/educational/learning/course.repo';
import { CourseModuleRepo } from './repositories/educational/learning/course.module.repo';
import { CourseContentRepo } from './repositories/educational/learning/course.content.repo';
import { UserLearningRepo } from './repositories/educational/learning/user.learning.repo';
import { DonorRepo } from './repositories/users/donor.repo';
import { HealthSystemRepo } from './repositories/hospitals/health.system.repo';
import { HospitalRepo } from './repositories/hospitals/hospital.repo';
import { NotificationRepo } from './repositories/general/notification.repo';
import { VolunteerRepo } from './repositories/users/volunteer.repo';
import { ChatRepo } from './repositories/community/chat.repo';
import { RssfeedRepo } from './repositories/general/rss.feed/rss.feed.repo';
import { RssfeedItemRepo } from './repositories/general/rss.feed/rss.feed.item.repo';
import { WearableDeviceDetailsRepo } from './repositories/webhook/webhook.wearable.device.details.repo';
import { UserGroupRepo } from './repositories/community/user.group.repo';
import { ReminderRepo } from './repositories/general/reminder.repo';
import { ReminderScheduleRepo } from './repositories/general/reminder.schedule.repo';
import { TenantRepo } from './repositories/tenant/tenant.repo';
import { CohortRepo } from './repositories/community/cohort.repo';
import { CustomQueryRepo } from './repositories/statistics/custom.query.repo';
import { DailyStatisticsRepo } from './repositories/statistics/daily.statistics.repo';

////////////////////////////////////////////////////////////////////////////////

export class SequelizeInjector {

    static registerInjections(container: DependencyContainer) {

        container.register('IPrimaryDatabaseConnector', DatabaseConnector_Sequelize);

        container.register('IPersonRepo', PersonRepo);
        container.register('IUserRepo', UserRepo);
        container.register('IPersonRoleRepo', PersonRoleRepo);
        container.register('IRoleRepo', RoleRepo);
        container.register('IOtpRepo', OtpRepo);
        container.register('ICustomerRepo', CustomerRepo);
        container.register('IPatientRepo', PatientRepo);
        container.register('IAddressRepo', AddressRepo);
        container.register('IRolePrivilegeRepo', RolePrivilegeRepo);
        container.register('IOrganizationRepo', OrganizationRepo);
        container.register('IDoctorRepo', DoctorRepo);
        container.register('IPatientHealthProfileRepo', HealthProfileRepo);
        container.register('IHealthProfileRepo', HealthProfileRepo);
        container.register('IInternalTestUserRepo', InternalTestUserRepo);
        container.register('IStepCountRepo', StepCountRepo);
        container.register('IFoodConsumptionRepo', FoodConsumptionRepo);
        container.register('IMoveMinutesRepo', MoveMinutesRepo);
        container.register('ICalorieBalanceRepo', CalorieBalanceRepo);
        container.register('IHeartPointsRepo', HeartPointsRepo);
        container.register('IPhysicalActivityRepo', PhysicalActivityRepo);
        container.register('IKnowledgeNuggetRepo', KnowledgeNuggetRepo);
        container.register('IWaterConsumptionRepo', WaterConsumptionRepo);
        container.register('IEmergencyContactRepo', EmergencyContactRepo);
        container.register('ISleepRepo', SleepRepo);
        container.register('IMeditationRepo', MeditationRepo);
        container.register('IFileResourceRepo', FileResourceRepo);
        container.register('IUserDeviceDetailsRepo', UserDeviceDetailsRepo);
        container.register('IGoalRepo', GoalRepo);
        container.register('IUserTaskRepo', UserTaskRepo);
        container.register('IHealthPriorityRepo', HealthPriorityRepo);
        container.register('IActionPlanRepo', ActionPlanRepo);
        container.register('IThirdpartyApiRepo', ThirdpartyApiRepo);
        container.register('ICustomTaskRepo', CustomTaskRepo);
        container.register('IFoodComponentMonitoringRepo', FoodComponentMonitoringRepo);
        container.register('IUserLoginSessionRepo', UserLoginSessionRepo);
        container.register('IStandRepo', StandRepo);
        container.register('INoticeRepo', NoticeRepo);
        container.register('ILearningPathRepo', LearningPathRepo);
        container.register('ICourseRepo', CourseRepo);
        container.register('ICourseModuleRepo', CourseModuleRepo);
        container.register('ICourseContentRepo', CourseContentRepo);
        container.register('IUserLearningRepo', UserLearningRepo);
        container.register('IDonorRepo', DonorRepo);
        container.register('IHealthSystemRepo', HealthSystemRepo);
        container.register('IHospitalRepo', HospitalRepo);
        container.register('INotificationRepo', NotificationRepo);
        container.register('IVolunteerRepo', VolunteerRepo);
        container.register('IChatRepo', ChatRepo);
        container.register('IRssfeedRepo', RssfeedRepo);
        container.register('IRssfeedItemRepo', RssfeedItemRepo);
        container.register('IWearableDeviceDetailsRepo', WearableDeviceDetailsRepo);
        container.register('IUserGroupRepo', UserGroupRepo);
        container.register('IReminderRepo', ReminderRepo);
        container.register('IReminderScheduleRepo', ReminderScheduleRepo);
        container.register('ITenantRepo', TenantRepo);
        container.register('ICohortRepo', CohortRepo);
        container.register('ICustomQueryRepo', CustomQueryRepo);
        container.register('IDailyStatisticsRepo', DailyStatisticsRepo);
    }

}
